name: Build and deploy Node.js app to Azure Web App - ismam-abid-portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4  # Updated from v3 to v4
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          # This check prevents the 254 error if package.json is missing
          if [ -f package.json ]; then
            npm install
            npm run build --if-present
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2296761F78134CC3A3686D86AC491D73 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D091C5ACFF824ACFBCADC96BDE3C221D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8256E939ED514FBCAEEBABE349FAD6A3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ismam-abid-portfolio'
          slot-name: 'Production'
          package: .
